-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  log_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  actor_type character varying NOT NULL CHECK (actor_type::text = ANY (ARRAY['PAWNER'::character varying, 'INVESTOR'::character varying, 'ADMIN'::character varying, 'SYSTEM'::character varying]::text[])),
  actor_id uuid,
  action character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id uuid,
  description text,
  metadata jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (log_id)
);
CREATE TABLE public.admin_users (
  admin_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  username character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  firstname character varying,
  lastname character varying,
  phone_number character varying,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['SUPER_ADMIN'::character varying, 'ADMIN'::character varying, 'MODERATOR'::character varying, 'SUPPORT'::character varying]::text[])),
  permissions jsonb,
  is_active boolean DEFAULT true,
  last_login_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT admin_users_pkey PRIMARY KEY (admin_id)
);
CREATE TABLE public.company_bank_accounts (
  account_id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_name character varying NOT NULL,
  account_number character varying NOT NULL,
  bank_name character varying NOT NULL,
  promptpay_number character varying,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_bank_accounts_pkey PRIMARY KEY (account_id)
);
CREATE TABLE public.contract_action_logs (
  log_id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid,
  customer_id uuid,
  investor_id uuid,
  action_request_id uuid,
  action_type character varying NOT NULL CHECK (action_type::text = ANY (ARRAY['CONTRACT_CREATED'::character varying, 'CONTRACT_SIGNED'::character varying, 'CONTRACT_ACTIVATED'::character varying, 'CONTRACT_COMPLETED'::character varying, 'FULL_REDEMPTION'::character varying, 'INTEREST_PAYMENT'::character varying, 'PRINCIPAL_REDUCTION'::character varying, 'PRINCIPAL_INCREASE'::character varying, 'SLIP_UPLOADED'::character varying, 'SLIP_VERIFIED'::character varying, 'SLIP_REJECTED'::character varying, 'PAYMENT_CONFIRMED'::character varying, 'PAYMENT_FAILED'::character varying, 'INVESTOR_APPROVED'::character varying, 'INVESTOR_REJECTED'::character varying, 'CONTRACT_EXTENDED'::character varying, 'CONTRACT_UPDATED'::character varying, 'NOTIFICATION_SENT'::character varying, 'ERROR_OCCURRED'::character varying]::text[])),
  action_status character varying DEFAULT 'COMPLETED'::character varying CHECK (action_status::text = ANY (ARRAY['INITIATED'::character varying, 'PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying]::text[])),
  amount numeric,
  principal_before numeric,
  principal_after numeric,
  interest_before numeric,
  interest_after numeric,
  total_amount numeric,
  contract_end_date_before date,
  contract_end_date_after date,
  slip_url text,
  slip_amount_detected numeric,
  slip_verification_result character varying CHECK (slip_verification_result::text = ANY (ARRAY['MATCHED'::character varying, 'UNDERPAID'::character varying, 'OVERPAID'::character varying, 'UNREADABLE'::character varying, 'INVALID'::character varying]::text[])),
  slip_verification_details jsonb,
  performed_by character varying CHECK (performed_by::text = ANY (ARRAY['PAWNER'::character varying, 'INVESTOR'::character varying, 'DROPPOINT'::character varying, 'SYSTEM'::character varying, 'ADMIN'::character varying]::text[])),
  performed_by_line_id character varying,
  performed_by_name character varying,
  description text,
  metadata jsonb,
  error_message text,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contract_action_logs_pkey PRIMARY KEY (log_id),
  CONSTRAINT contract_action_logs_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(contract_id),
  CONSTRAINT contract_action_logs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.pawners(customer_id),
  CONSTRAINT contract_action_logs_investor_id_fkey FOREIGN KEY (investor_id) REFERENCES public.investors(investor_id)
);
CREATE TABLE public.contract_action_requests (
  request_id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  request_type character varying NOT NULL CHECK (request_type::text = ANY (ARRAY['INTEREST_PAYMENT'::character varying, 'PRINCIPAL_REDUCTION'::character varying, 'PRINCIPAL_INCREASE'::character varying]::text[])),
  request_status character varying DEFAULT 'PENDING'::character varying CHECK (request_status::text = ANY (ARRAY['PENDING'::character varying, 'AWAITING_PAYMENT'::character varying, 'SLIP_UPLOADED'::character varying, 'SLIP_VERIFIED'::character varying, 'SLIP_REJECTED'::character varying, 'SLIP_REJECTED_FINAL'::character varying, 'AWAITING_SIGNATURE'::character varying, 'AWAITING_INVESTOR_APPROVAL'::character varying, 'PENDING_INVESTOR_APPROVAL'::character varying, 'INVESTOR_APPROVED'::character varying, 'INVESTOR_REJECTED'::character varying, 'AWAITING_INVESTOR_PAYMENT'::character varying, 'INVESTOR_SLIP_UPLOADED'::character varying, 'INVESTOR_SLIP_VERIFIED'::character varying, 'INVESTOR_SLIP_REJECTED'::character varying, 'INVESTOR_SLIP_REJECTED_FINAL'::character varying, 'INVESTOR_TRANSFERRED'::character varying, 'AWAITING_PAWNER_CONFIRM'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'VOIDED'::character varying]::text[])),
  principal_before numeric NOT NULL,
  interest_rate numeric NOT NULL,
  daily_interest_rate numeric,
  contract_start_date date NOT NULL,
  contract_end_date_before date NOT NULL,
  days_in_contract integer NOT NULL,
  days_elapsed integer NOT NULL,
  days_remaining integer NOT NULL,
  interest_accrued numeric NOT NULL,
  interest_to_pay numeric,
  new_end_date date,
  reduction_amount numeric,
  interest_for_period numeric,
  total_to_pay_reduction numeric,
  principal_after_reduction numeric,
  new_interest_for_remaining numeric,
  increase_amount numeric,
  principal_after_increase numeric,
  new_interest_for_remaining_increase numeric,
  total_amount numeric,
  slip_url text,
  slip_uploaded_at timestamp with time zone,
  slip_amount_detected numeric,
  slip_verification_result character varying,
  slip_verification_details jsonb,
  slip_attempt_count integer DEFAULT 0,
  investor_slip_url text,
  investor_slip_uploaded_at timestamp with time zone,
  investor_slip_amount_detected numeric,
  investor_slip_verification_result character varying,
  investor_slip_verification_details jsonb,
  investor_slip_attempt_count integer DEFAULT 0,
  pawner_bank_name character varying,
  pawner_bank_account_no character varying,
  pawner_bank_account_name character varying,
  pawner_signature_url text,
  signature_url text,
  signed_at timestamp with time zone,
  investor_approved_at timestamp with time zone,
  investor_rejected_at timestamp with time zone,
  investor_rejection_reason text,
  pawner_confirmed_at timestamp with time zone,
  pawner_rejected_at timestamp with time zone,
  terms_accepted boolean DEFAULT false,
  terms_accepted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  voided_at timestamp with time zone,
  void_reason text,
  CONSTRAINT contract_action_requests_pkey PRIMARY KEY (request_id),
  CONSTRAINT contract_action_requests_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(contract_id)
);
CREATE TABLE public.contracts (
  contract_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_number character varying NOT NULL UNIQUE,
  customer_id uuid NOT NULL,
  investor_id uuid,
  drop_point_id uuid,
  item_id uuid NOT NULL,
  loan_request_id uuid,
  loan_offer_id uuid,
  contract_start_date timestamp without time zone NOT NULL DEFAULT now(),
  contract_end_date timestamp without time zone NOT NULL,
  contract_duration_days integer NOT NULL,
  loan_principal_amount numeric NOT NULL,
  interest_rate numeric NOT NULL,
  interest_amount numeric NOT NULL,
  total_amount numeric NOT NULL,
  platform_fee_rate numeric NOT NULL DEFAULT 0.50,
  platform_fee_amount numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  interest_paid numeric DEFAULT 0,
  principal_paid numeric DEFAULT 0,
  contract_status character varying DEFAULT 'ACTIVE'::character varying CHECK (contract_status::text = ANY (ARRAY['PENDING_SIGNATURE'::character varying, 'ACTIVE'::character varying, 'CONFIRMED'::character varying, 'COMPLETED'::character varying, 'DEFAULTED'::character varying, 'EXTENDED'::character varying, 'TERMINATED'::character varying, 'LIQUIDATED'::character varying]::text[])),
  funding_status character varying DEFAULT 'PENDING'::character varying CHECK (funding_status::text = ANY (ARRAY['PENDING'::character varying, 'FUNDED'::character varying, 'DISBURSED'::character varying]::text[])),
  parent_contract_id uuid,
  original_contract_id uuid,
  contract_file_url text,
  signed_contract_url text,
  funded_at timestamp without time zone,
  disbursed_at timestamp without time zone,
  completed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  item_delivery_status character varying DEFAULT 'PENDING'::character varying CHECK (item_delivery_status::text = ANY (ARRAY['PENDING'::character varying, 'PAWNER_CONFIRMED'::character varying, 'IN_TRANSIT'::character varying, 'RECEIVED_AT_DROP_POINT'::character varying, 'VERIFIED'::character varying, 'RETURNED'::character varying]::text[])),
  item_received_at timestamp without time zone,
  item_verified_at timestamp without time zone,
  payment_slip_url text,
  payment_confirmed_at timestamp without time zone,
  payment_status character varying,
  redemption_status character varying CHECK (redemption_status::text = ANY (ARRAY['NONE'::character varying, 'PENDING'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying]::text[])),
  original_principal_amount numeric,
  current_principal_amount numeric,
  total_interest_paid numeric DEFAULT 0,
  total_principal_reduced numeric DEFAULT 0,
  total_principal_increased numeric DEFAULT 0,
  extension_count integer DEFAULT 0,
  last_action_date timestamp with time zone,
  last_action_type character varying,
  CONSTRAINT contracts_pkey PRIMARY KEY (contract_id),
  CONSTRAINT contracts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.pawners(customer_id),
  CONSTRAINT contracts_investor_id_fkey FOREIGN KEY (investor_id) REFERENCES public.investors(investor_id),
  CONSTRAINT contracts_drop_point_id_fkey FOREIGN KEY (drop_point_id) REFERENCES public.drop_points(drop_point_id),
  CONSTRAINT contracts_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id),
  CONSTRAINT contracts_loan_request_id_fkey FOREIGN KEY (loan_request_id) REFERENCES public.loan_requests(request_id),
  CONSTRAINT contracts_loan_offer_id_fkey FOREIGN KEY (loan_offer_id) REFERENCES public.loan_offers(offer_id),
  CONSTRAINT contracts_parent_contract_id_fkey FOREIGN KEY (parent_contract_id) REFERENCES public.contracts(contract_id),
  CONSTRAINT contracts_original_contract_id_fkey FOREIGN KEY (original_contract_id) REFERENCES public.contracts(contract_id)
);
CREATE TABLE public.drop_point_verifications (
  verification_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  drop_point_id uuid NOT NULL,
  item_id uuid NOT NULL,
  brand_correct boolean,
  model_correct boolean,
  capacity_correct boolean,
  color_match boolean,
  functionality_ok boolean,
  mdm_lock_status boolean,
  condition_score integer CHECK (condition_score >= 0 AND condition_score <= 100),
  verification_photos ARRAY,
  notes text,
  verification_result character varying CHECK (verification_result::text = ANY (ARRAY['APPROVED'::character varying, 'REJECTED'::character varying, 'PENDING'::character varying]::text[])),
  rejection_reason text,
  verified_by_line_id character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT drop_point_verifications_pkey PRIMARY KEY (verification_id),
  CONSTRAINT drop_point_verifications_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(contract_id),
  CONSTRAINT drop_point_verifications_drop_point_id_fkey FOREIGN KEY (drop_point_id) REFERENCES public.drop_points(drop_point_id),
  CONSTRAINT drop_point_verifications_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id)
);
CREATE TABLE public.drop_points (
  drop_point_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  drop_point_name character varying NOT NULL,
  drop_point_code character varying NOT NULL UNIQUE,
  phone_number character varying NOT NULL,
  email character varying,
  addr_house_no character varying,
  addr_village character varying,
  addr_street character varying,
  addr_sub_district character varying,
  addr_district character varying,
  addr_province character varying,
  addr_country character varying DEFAULT 'Thailand'::character varying,
  addr_postcode character varying,
  google_map_url text,
  latitude numeric,
  longitude numeric,
  opening_hours jsonb,
  capacity integer DEFAULT 100,
  current_items_count integer DEFAULT 0,
  manager_name character varying,
  manager_phone character varying,
  manager_line_id character varying,
  is_active boolean DEFAULT true,
  is_accepting_items boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  line_id character varying UNIQUE,
  CONSTRAINT drop_points_pkey PRIMARY KEY (drop_point_id)
);
CREATE TABLE public.investors (
  investor_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  line_id character varying NOT NULL UNIQUE,
  firstname character varying NOT NULL,
  lastname character varying NOT NULL,
  investor_signature_id character varying,
  phone_number character varying NOT NULL CHECK (phone_number::text ~ '^\+?[0-9]{9,15}$'::text),
  national_id character varying UNIQUE,
  email character varying,
  addr_house_no character varying,
  addr_village character varying,
  addr_street character varying,
  addr_sub_district character varying,
  addr_district character varying,
  addr_province character varying,
  addr_country character varying DEFAULT 'Thailand'::character varying,
  addr_postcode character varying,
  kyc_status character varying DEFAULT 'NOT_VERIFIED'::character varying CHECK (kyc_status::text = ANY (ARRAY['NOT_VERIFIED'::character varying, 'PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying]::text[])),
  uppass_slug character varying UNIQUE,
  kyc_verified_at timestamp without time zone,
  kyc_rejection_reason text,
  kyc_data jsonb,
  bank_name character varying,
  bank_account_no character varying,
  bank_account_type character varying CHECK (bank_account_type IS NULL OR (bank_account_type::text = ANY (ARRAY['บัญชีออมทรัพย์'::character varying, 'บัญชีเงินฝากประจำ'::character varying, 'บัญชีกระแสรายวัน'::character varying, 'บัญชีเงินตราต่างประเทศ'::character varying, 'พร้อมเพย์'::character varying]::text[]))),
  bank_account_name character varying,
  auto_invest_enabled boolean DEFAULT false,
  preferred_loan_types ARRAY,
  min_investment_amount numeric DEFAULT 1000,
  max_investment_amount numeric,
  is_active boolean DEFAULT true,
  is_blocked boolean DEFAULT false,
  blocked_reason text,
  investor_tier character varying DEFAULT 'STANDARD'::character varying CHECK (investor_tier::text = ANY (ARRAY['STANDARD'::character varying, 'PREMIUM'::character varying, 'VIP'::character varying]::text[])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  last_login_at timestamp without time zone,
  promptpay_number character varying,
  promptpay_name character varying,
  ekyc_url text,
  CONSTRAINT investors_pkey PRIMARY KEY (investor_id)
);
CREATE TABLE public.item_lenses (
  lens_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid NOT NULL,
  lens_model character varying NOT NULL,
  lens_serial_number character varying,
  lens_condition integer CHECK (lens_condition >= 0 AND lens_condition <= 100),
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT item_lenses_pkey PRIMARY KEY (lens_id),
  CONSTRAINT item_lenses_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id)
);
CREATE TABLE public.item_valuations (
  valuation_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid NOT NULL,
  valuation_type character varying NOT NULL CHECK (valuation_type::text = ANY (ARRAY['AI_INITIAL'::character varying, 'MANUAL_REVIEW'::character varying, 'DROP_POINT_VERIFY'::character varying]::text[])),
  valuated_by character varying,
  estimated_value numeric NOT NULL,
  condition_score integer,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT item_valuations_pkey PRIMARY KEY (valuation_id),
  CONSTRAINT item_valuations_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id)
);
CREATE TABLE public.items (
  item_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid,
  item_type character varying NOT NULL CHECK (item_type::text = ANY (ARRAY['โทรศัพท์มือถือ'::character varying, 'อุปกรณ์เสริมโทรศัพท์'::character varying, 'กล้อง'::character varying, 'Apple'::character varying, 'โน้ตบุค'::character varying]::text[])),
  brand character varying NOT NULL,
  model character varying NOT NULL,
  capacity character varying,
  serial_number character varying,
  cpu character varying,
  ram character varying,
  storage character varying,
  gpu character varying,
  item_condition integer CHECK (item_condition >= 0 AND item_condition <= 100),
  ai_condition_score numeric,
  ai_condition_reason text,
  estimated_value numeric NOT NULL,
  ai_confidence numeric,
  accessories text,
  defects text,
  notes text,
  image_urls ARRAY NOT NULL,
  item_status character varying DEFAULT 'PENDING'::character varying CHECK (item_status::text = ANY (ARRAY['DRAFT'::character varying, 'PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'IN_CONTRACT'::character varying, 'RETURNED'::character varying, 'LIQUIDATED'::character varying]::text[])),
  drop_point_id uuid,
  received_at_drop_point timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  verified_by_drop_point boolean DEFAULT false,
  drop_point_verified_at timestamp without time zone,
  drop_point_verification_notes text,
  drop_point_photos ARRAY,
  drop_point_condition_score integer CHECK (drop_point_condition_score >= 0 AND drop_point_condition_score <= 100),
  line_id character varying,
  color character varying,
  screen_size character varying,
  watch_size character varying,
  watch_connectivity character varying,
  CONSTRAINT items_pkey PRIMARY KEY (item_id),
  CONSTRAINT items_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.pawners(customer_id),
  CONSTRAINT items_drop_point_id_fkey FOREIGN KEY (drop_point_id) REFERENCES public.drop_points(drop_point_id)
);
CREATE TABLE public.loan_offers (
  offer_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  investor_id uuid NOT NULL,
  offer_amount numeric NOT NULL,
  interest_rate numeric NOT NULL,
  duration_days integer NOT NULL,
  offer_status character varying DEFAULT 'PENDING'::character varying CHECK (offer_status::text = ANY (ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'EXPIRED'::character varying, 'WITHDRAWN'::character varying]::text[])),
  expires_at timestamp without time zone,
  accepted_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT loan_offers_pkey PRIMARY KEY (offer_id),
  CONSTRAINT loan_offers_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.loan_requests(request_id),
  CONSTRAINT loan_offers_investor_id_fkey FOREIGN KEY (investor_id) REFERENCES public.investors(investor_id)
);
CREATE TABLE public.loan_requests (
  request_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  requested_amount numeric NOT NULL,
  requested_duration_days integer NOT NULL,
  drop_point_id uuid,
  delivery_method character varying CHECK (delivery_method::text = ANY (ARRAY['WALK_IN'::character varying, 'DELIVERY'::character varying, 'COURIER'::character varying]::text[])),
  delivery_fee numeric DEFAULT 0,
  request_status character varying DEFAULT 'PENDING'::character varying CHECK (request_status::text = ANY (ARRAY['PENDING'::character varying, 'AWAITING_OFFERS'::character varying, 'OFFER_ACCEPTED'::character varying, 'FUNDED'::character varying, 'REJECTED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying]::text[])),
  expires_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT loan_requests_pkey PRIMARY KEY (request_id),
  CONSTRAINT loan_requests_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(item_id),
  CONSTRAINT loan_requests_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.pawners(customer_id),
  CONSTRAINT loan_requests_drop_point_id_fkey FOREIGN KEY (drop_point_id) REFERENCES public.drop_points(drop_point_id)
);
CREATE TABLE public.notifications (
  notification_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recipient_type character varying NOT NULL CHECK (recipient_type::text = ANY (ARRAY['PAWNER'::character varying, 'INVESTOR'::character varying, 'ADMIN'::character varying]::text[])),
  recipient_id uuid NOT NULL,
  notification_type character varying NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  related_entity_type character varying,
  related_entity_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp without time zone,
  sent_via ARRAY DEFAULT ARRAY['IN_APP'::text],
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);
CREATE TABLE public.pawn_ticket_generation_queue (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL UNIQUE,
  status character varying DEFAULT 'PENDING'::character varying CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying]::text[])),
  attempts integer DEFAULT 0,
  error_message text,
  created_at timestamp without time zone DEFAULT now(),
  processed_at timestamp without time zone,
  CONSTRAINT pawn_ticket_generation_queue_pkey PRIMARY KEY (id),
  CONSTRAINT pawn_ticket_generation_queue_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(contract_id)
);
CREATE TABLE public.pawners (
  customer_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  line_id character varying NOT NULL UNIQUE,
  firstname character varying NOT NULL,
  lastname character varying NOT NULL,
  customer_signature_id character varying,
  phone_number character varying NOT NULL CHECK (phone_number::text ~ '^\+?[0-9]{9,15}$'::text),
  national_id character varying UNIQUE,
  email character varying,
  addr_house_no character varying,
  addr_village character varying,
  addr_street character varying,
  addr_sub_district character varying,
  addr_district character varying,
  addr_province character varying,
  addr_country character varying DEFAULT 'Thailand'::character varying,
  addr_postcode character varying,
  kyc_status character varying DEFAULT 'NOT_VERIFIED'::character varying CHECK (kyc_status::text = ANY (ARRAY['NOT_VERIFIED'::character varying, 'PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying]::text[])),
  uppass_slug character varying UNIQUE,
  kyc_verified_at timestamp without time zone,
  kyc_rejection_reason text,
  kyc_data jsonb,
  bank_name character varying,
  bank_account_no character varying,
  bank_account_type character varying CHECK (bank_account_type IS NULL OR (bank_account_type::text = ANY (ARRAY['บัญชีออมทรัพย์'::character varying, 'บัญชีเงินฝากประจำ'::character varying, 'บัญชีกระแสรายวัน'::character varying, 'บัญชีเงินตราต่างประเทศ'::character varying, 'พร้อมเพย์'::character varying]::text[]))),
  bank_account_name character varying,
  is_active boolean DEFAULT true,
  is_blocked boolean DEFAULT false,
  blocked_reason text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  last_login_at timestamp without time zone,
  promptpay_number character varying,
  ekyc_url text,
  signature_url text,
  CONSTRAINT pawners_pkey PRIMARY KEY (customer_id)
);
CREATE TABLE public.payments (
  payment_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  payment_type character varying NOT NULL CHECK (payment_type::text = ANY (ARRAY['PRINCIPAL'::character varying, 'INTEREST'::character varying, 'FULL_REPAYMENT'::character varying, 'PARTIAL_REPAYMENT'::character varying, 'LATE_FEE'::character varying, 'EXTENSION_FEE'::character varying]::text[])),
  amount numeric NOT NULL,
  principal_portion numeric DEFAULT 0,
  interest_portion numeric DEFAULT 0,
  fee_portion numeric DEFAULT 0,
  payment_method character varying CHECK (payment_method::text = ANY (ARRAY['BANK_TRANSFER'::character varying, 'PROMPTPAY'::character varying, 'CREDIT_CARD'::character varying, 'CASH'::character varying, 'WALLET'::character varying]::text[])),
  payment_status character varying DEFAULT 'PENDING'::character varying CHECK (payment_status::text = ANY (ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying]::text[])),
  transaction_ref character varying,
  payment_slip_url text,
  bank_name character varying,
  verified_by uuid,
  verified_at timestamp without time zone,
  payment_date timestamp without time zone DEFAULT now(),
  notes text,
  metadata jsonb,
  created_at timestamp without time zone DEFAULT now(),
  payer_type character varying CHECK (payer_type::text = ANY (ARRAY['INVESTOR'::character varying, 'PAWNER'::character varying]::text[])),
  payer_id uuid,
  confirmed_by_recipient boolean DEFAULT false,
  confirmed_at timestamp without time zone,
  confirmation_deadline timestamp without time zone,
  paid_by_investor_id uuid,
  redemption_id uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (payment_id),
  CONSTRAINT payments_paid_by_investor_id_fkey FOREIGN KEY (paid_by_investor_id) REFERENCES public.investors(investor_id),
  CONSTRAINT payments_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(contract_id),
  CONSTRAINT payments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.admin_users(admin_id),
  CONSTRAINT payments_redemption_id_fkey FOREIGN KEY (redemption_id) REFERENCES public.redemption_requests(redemption_id)
);
CREATE TABLE public.platform_revenue (
  revenue_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid,
  revenue_type character varying NOT NULL CHECK (revenue_type::text = ANY (ARRAY['INTEREST_FEE'::character varying, 'LATE_FEE'::character varying, 'EXTENSION_FEE'::character varying, 'LIQUIDATION_FEE'::character varying, 'SERVICE_FEE'::character varying]::text[])),
  amount numeric NOT NULL,
  description text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT platform_revenue_pkey PRIMARY KEY (revenue_id),
  CONSTRAINT platform_revenue_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(contract_id)
);
CREATE TABLE public.redemption_requests (
  redemption_id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  request_type character varying NOT NULL CHECK (request_type::text = ANY (ARRAY['FULL_REDEMPTION'::character varying, 'INTEREST_PAYMENT'::character varying, 'PRINCIPAL_REDUCTION'::character varying, 'PRINCIPAL_INCREASE'::character varying]::text[])),
  principal_amount numeric NOT NULL,
  interest_amount numeric NOT NULL,
  delivery_fee numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  reduction_amount numeric,
  increase_amount numeric,
  delivery_method character varying CHECK (delivery_method::text = ANY (ARRAY['SELF_PICKUP'::character varying, 'SELF_ARRANGE'::character varying, 'PLATFORM_ARRANGE'::character varying]::text[])),
  delivery_address_full text,
  delivery_addr_house_no character varying,
  delivery_addr_village character varying,
  delivery_addr_street character varying,
  delivery_addr_sub_district character varying,
  delivery_addr_district character varying,
  delivery_addr_province character varying,
  delivery_addr_postcode character varying,
  delivery_contact_phone character varying,
  delivery_notes text,
  payment_slip_url text,
  payment_slip_uploaded_at timestamp with time zone,
  request_status character varying DEFAULT 'PENDING'::character varying CHECK (request_status::text = ANY (ARRAY['PENDING'::character varying, 'SLIP_UPLOADED'::character varying, 'AMOUNT_VERIFIED'::character varying, 'AMOUNT_MISMATCH'::character varying, 'PREPARING_ITEM'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'PAWNER_CONFIRMED'::character varying, 'INVESTOR_CONFIRMED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'REJECTED'::character varying]::text[])),
  verified_by_drop_point_id uuid,
  verified_by_line_id character varying,
  verified_at timestamp with time zone,
  verification_notes text,
  actual_amount_received numeric,
  amount_difference numeric,
  mismatch_type character varying CHECK (mismatch_type::text = ANY (ARRAY['OVERPAID'::character varying, 'UNDERPAID'::character varying]::text[])),
  mismatch_resolved boolean DEFAULT false,
  mismatch_resolved_at timestamp with time zone,
  tracking_number character varying,
  courier_name character varying,
  pawner_confirmed_at timestamp with time zone,
  investor_confirmed_at timestamp with time zone,
  investor_interest_earned numeric,
  platform_fee_deducted numeric,
  investor_net_profit numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pawner_receipt_photos ARRAY,
  pawner_receipt_uploaded_at timestamp with time zone,
  pawner_receipt_verified boolean DEFAULT false,
  support_contact_used character varying,
  item_return_confirmed_at timestamp with time zone,
  final_completion_at timestamp with time zone,
  CONSTRAINT redemption_requests_pkey PRIMARY KEY (redemption_id),
  CONSTRAINT redemption_requests_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(contract_id),
  CONSTRAINT redemption_requests_verified_by_drop_point_id_fkey FOREIGN KEY (verified_by_drop_point_id) REFERENCES public.drop_points(drop_point_id)
);
CREATE TABLE public.repayment_schedules (
  schedule_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  due_date date NOT NULL,
  amount_due numeric NOT NULL,
  principal_due numeric NOT NULL,
  interest_due numeric NOT NULL,
  amount_paid numeric DEFAULT 0,
  schedule_status character varying DEFAULT 'PENDING'::character varying CHECK (schedule_status::text = ANY (ARRAY['PENDING'::character varying, 'PAID'::character varying, 'PARTIAL_PAID'::character varying, 'OVERDUE'::character varying, 'WAIVED'::character varying]::text[])),
  paid_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT repayment_schedules_pkey PRIMARY KEY (schedule_id),
  CONSTRAINT repayment_schedules_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(contract_id)
);
CREATE TABLE public.slip_verifications (
  verification_id uuid NOT NULL DEFAULT gen_random_uuid(),
  action_request_id uuid,
  redemption_id uuid,
  slip_url text NOT NULL,
  expected_amount numeric NOT NULL,
  detected_amount numeric,
  amount_difference numeric,
  verification_result character varying CHECK (verification_result::text = ANY (ARRAY['MATCHED'::character varying, 'UNDERPAID'::character varying, 'OVERPAID'::character varying, 'UNREADABLE'::character varying, 'INVALID'::character varying]::text[])),
  confidence_score numeric,
  ai_model character varying DEFAULT 'gpt-4o-mini'::character varying,
  ai_response jsonb,
  ai_raw_response text,
  attempt_number integer DEFAULT 1,
  verified_by character varying DEFAULT 'AI'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT slip_verifications_pkey PRIMARY KEY (verification_id),
  CONSTRAINT slip_verifications_action_request_id_fkey FOREIGN KEY (action_request_id) REFERENCES public.contract_action_requests(request_id),
  CONSTRAINT slip_verifications_redemption_id_fkey FOREIGN KEY (redemption_id) REFERENCES public.redemption_requests(redemption_id)
);
CREATE TABLE public.support_contacts (
  contact_id uuid NOT NULL DEFAULT gen_random_uuid(),
  contact_type character varying NOT NULL CHECK (contact_type::text = ANY (ARRAY['PHONE'::character varying, 'EMAIL'::character varying, 'LINE'::character varying]::text[])),
  contact_value character varying NOT NULL,
  display_name character varying NOT NULL,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_contacts_pkey PRIMARY KEY (contact_id)
);
CREATE TABLE public.wallet_transactions (
  transaction_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  wallet_id uuid NOT NULL,
  transaction_type character varying NOT NULL CHECK (transaction_type::text = ANY (ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying, 'COMMITMENT'::character varying, 'COMMITMENT_RELEASE'::character varying, 'INVESTMENT'::character varying, 'REPAYMENT'::character varying, 'INTEREST_EARNED'::character varying, 'FEE'::character varying, 'REFUND'::character varying]::text[])),
  amount numeric NOT NULL,
  balance_before numeric NOT NULL,
  balance_after numeric NOT NULL,
  reference_type character varying,
  reference_id uuid,
  description text,
  metadata jsonb,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT wallet_transactions_pkey PRIMARY KEY (transaction_id),
  CONSTRAINT wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallets(wallet_id)
);
CREATE TABLE public.wallets (
  wallet_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  investor_id uuid NOT NULL UNIQUE,
  available_balance numeric DEFAULT 0 CHECK (available_balance >= 0::numeric),
  committed_balance numeric DEFAULT 0 CHECK (committed_balance >= 0::numeric),
  total_balance numeric DEFAULT (available_balance + committed_balance),
  maximum_commitment numeric,
  total_invested numeric DEFAULT 0,
  total_earned numeric DEFAULT 0,
  total_withdrawn numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT wallets_pkey PRIMARY KEY (wallet_id),
  CONSTRAINT wallets_investor_id_fkey FOREIGN KEY (investor_id) REFERENCES public.investors(investor_id)
);
